name: Media Display Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "Media_Display/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: Media_Display/
            shell: bash
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4     
        - name: Build Docker Image
          run: |
           docker build -t  ${{secrets.REPO_URL}}display:${{github.sha}}  .  

        - name: Auth to Google Cloud
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}  

        - name: Configure Docker for Artifact Registry
          run: gcloud auth configure-docker us-east1-docker.pkg.dev    

        - name: Push Image
          run:  docker push ${{secrets.REPO_URL}}display:${{github.sha}}

        - name: Update Cloud Run Media display
          run: |
             gcloud run deploy media-display \
             --image=${{secrets.REPO_URL}}display:${{github.sha}} \
             --region=us-east1